version: '3'

services:
    weather-forecast:
        image: protest
        container_name: postgres-db
        environment:
            - POSTGRES_USER=devtools_user
            - POSTGRES_PASSWORD=DevTools1!
            - POSTGRES_DB=devtools_db
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data


    rabbit-mq:
        image: rabbitmq:3.7-management
        container_name: rabbit-mq
        environment:
                - RABBITMQ_DEFAULT_USER=devtools_user
                - RABBITMQ_DEFAULT_PASS=DevTools1!
        ports:
                - "15672:15672"
                - "5672:5672"

volumes:
        pgdata:
                external: true