version: '3'

services:
    prometheus-example-webapi:
        image: prometheus-example-webapi
        container_name: prometheus-example-webapi
        ports:
            - "5001:80"
            - "9091:1234"

    prometheus-example-host:
        image: prometheus-example-host
        container_name: prometheus-example-host
        ports:
            - "9092:1234"
            