FROM bitnami/prometheus

COPY ./prometheus-collector/* /prometheus
# USER root


# RUN apt update && apt install -y curl wget

# ENV RELEASE="2.2.1"

# RUN wget https://github.com/prometheus/prometheus/releases/download/v${RELEASE}/prometheus-${RELEASE}.linux-amd64.tar.gz

# RUN tar xvf prometheus-${RELEASE}.linux-amd64.tar.gz

# RUN cd prometheus-${RELEASE}.linux-amd64/

# WORKDIR /prometheus-2.2.1.linux-amd64

# RUN chmod +x prometheus

#CMD ["prometheus"]

#EXPOSE 80

